import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';

import '../assets/scss/style.scss'
import NavBar from "@/components/common/NavBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar/> 
        {children}
        </body>
    </html>
  );
}
