import 'bootstrap/dist/css/bootstrap.min.css';

import '../assets/scss/style.scss';
import NavBar from "@/components/common/NavBar";

export const metadata = {
  title: "portfolio",
  description: "Generated by create next app",
  keywords:"web,web developer,react js, js, javascript, redux, fronted developer"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar/> 
        {children}
        </body>
    </html>
  );
}
